CREATE TABLE usuarios(
	id BIGSERIAL PRIMARY KEY,
	correo VARCHAR (255)	NOT NULL,
	nombre VARCHAR(255) NOT NULL,
	apellidoP VARCHAR(255) NOT NULL,
	apellidoM VARCHAR(255) NOT NULL,
	contrasena VARCHAR(255) NOT NULL,
	disponible BOOLEAN NULL,
	token_sesion VARCHAR(255) NULL,
	creacion TIMESTAMP(0) NOT NULL,
	actualizacion TIMESTAMP(0) NOT NULL
	
);